### ISSUE TITLE
Add support for DB options

### ISSUE THREAD

**Issue by trauta** [voxpupuli/puppet-icingadb#35]
Hi,

unfortunately, it is currently not possible to configure custom db options with this module. In my setup I need to set the `wsrep_sync_wait` parameter to `0` because both Icinga master nodes only connect to their local MariaDB daemon.

Could you please add the [database options](https://icinga.com/docs/icinga-db/latest/doc/03-Configuration/#database-options) parameters?

Regards,
Alex

**Comment by lbetz** [comment]
Right, thx, will be added shortly.

**Comment by trauta** [comment]
Sorry to bother again, but is there any specific reason why the `wsrep_sync_wait` parameter is set to `Integer[1]` which prevents using `0`?

The [IcingaDB documentation](https://icinga.com/docs/icinga-db/latest/doc/03-Configuration/#galera-cluster) says that for Galera setups where the Icinga master nodes only connects to a single DB node the setting should be set to `0`, however the current implementation with the `Integer[1]` datatype does not allow this.

```
Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Class[Icingadb]: parameter 'db_options' entry 'wsrep_sync_wait' expects an Integer[1] value, got Integer[0, 0]
```

**Comment by lbetz** [comment]
I think the reason is that I wasn't paying attention.
