### ISSUE TITLE
Add missing redis module dependency

### ISSUE THREAD

**Issue by trauta** [voxpupuli/puppet-icingadb#43]
Hi,

just a small hint, unfortunately there is no hint in the documentation that this module depends on the upstream `puppet-redis` module. 

I think this should be added to the requirements section in the README file for example.

**Comment by lbetz** [comment]
This module uses the class icinga::redis and so depends on module puppet-icinga. The module puppet-icinga uses redis and so that module depends on puppet-redis.

**Comment by lbetz** [comment]
Sorry, you're right.  The defined resource of type redis::instance is also used so the dependency is really misssing.
